### ISSUE TITLE
Couldn't login

### ISSUE THREAD

**Issue by itsmenow1** [ahmedayman4a/LyndaCoursesDownloader#10]
I couldn't login with logs below

2020-12-04 17:38:06.601 +07:00 [INF] Restoring config file
2020-12-04 17:38:06.657 +07:00 [INF] No config file to restore is found
2020-12-04 17:38:07.380 +07:00 [INF] Acquired data from config
2020-12-04 17:38:09.851 +07:00 [INF] Checking for updates...
2020-12-04 17:38:11.414 +07:00 [INF] Logging in
2020-12-04 17:38:12.601 +07:00 [INF] No updates detected.
2020-12-04 17:38:18.337 +07:00 [ERR] Unknown Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LyndaCoursesDownloader.CourseExtractor.Extractor.<>c__DisplayClass11_0.<Login>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at LyndaCoursesDownloader.GUIDownloader.MainForm.ExtractCourse()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at LyndaCoursesDownloader.CourseExtractor.Extractor.<>c__DisplayClass11_0.<Login>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Please help

Thank you in advanced

**Comment by ahmedayman4a** [comment]
**tdlr : The chromedriver needs to be updated to the same version as your chrome browser.**

<h2> Long Explanation : </h2>

Chromedriver is how the program communicates with chrome and controls it. Everytime chrome is updated the chromedriver needs to be updated too. Firefox doesn't cause the same problem. You can update firefox without ever needing to update the firefox driver. That's why I recommend using firefox instead of chrome.

If you still want to use chrome then you have to:

- Check your google chrome browser version by going to Settings > About Chrome
- Go to the [chromedriver website](https://chromedriver.chromium.org/downloads) and download the version that matches your chrome version and your platform (windows, mac, linux).
-  Extract the zip file, copy the `chromedriver.exe` executable, paste it at this location : `%localappdata%\LyndaCoursesDownloader\app-1.0.1` and click on `Replace the file in the destination`.

 You have to do this tedious process everytime chrome updates. This is something out of my hand. Again, this is why I recommend using firefox with my downlaoder. You don't have to do any of this if you use firefox.
